services:
  web-fe:
    build: . # . means dockerfile contains in same folder
    command: python app.py
    ports:
      - 5000:5000
  redis:
    image: "redis:alpine" # using image from docker hub
    ports:
      - 6379